[general]
import = [
    "./themes/catppuccin_mocha.toml"
]

[terminal]
shell = { program = "wsl.exe", args = ["~",] }

[window]
startup_mode = "Maximized"
padding = { x = 3, y = 3 }

[font]
size = 12

[font.normal]
family = "MesloLGS NF"

[mouse]
bindings = [
    { mouse = "Right", action = "Paste" },
]

[keyboard]
bindings = [
    { key = "Insert", mods = "Control", action = "Copy" },
    { key = "Insert", mods = "Shift", action = "Paste" },
]

[selection]
save_to_clipboard = true

[cursor]
style = { blinking = "Always"}